name: Android CI (native + web)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  native:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install deps
        run: npm ci

      - name: Boot emulator + run native smoke
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_5
          force-avd-creation: true
          disable-animations: true
          emulator-boot-timeout: 900
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -no-boot-anim -camera-back none -camera-front none
          script: |
            npx appium driver install uiautomator2
            npx appium --base-path /wd/hub --log-level info & sleep 6
            adb devices
            npx wdio run wdio.conf.ts --spec test/specs/smoke.native.e2e.ts

      - name: Generate Allure (native)
        if: ${{ hashFiles('allure-results/**') != '' }}
        run: npx allure-commandline generate --clean ./allure-results -o ./allure-report

      - name: Upload Allure results (native)
        if: ${{ hashFiles('allure-results/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: native-allure-results
          path: allure-results

      - name: Upload Allure report (native)
        if: ${{ hashFiles('allure-report/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: native-allure-report
          path: allure-report

      - name: Collect diagnostics (native)
        if: ${{ failure() }}
        run: |
          adb logcat -d > native-logcat.txt || true
          adb shell getprop > native-getprop.txt || true
        shell: bash

      - name: Upload diagnostics (native)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: native-diagnostics
          path: |
            native-logcat.txt
            native-getprop.txt

  web:
    runs-on: ubuntu-latest
    needs: native
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install deps
        run: npm ci

      - name: Boot emulator + run web smoke
        uses: reactivecircus/android-emulator-runner@v2
        env:
          CHROME_APK_URL: ${{ secrets.CHROME_APK_URL }}
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_5
          force-avd-creation: true
          disable-animations: true
          emulator-boot-timeout: 900
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -no-boot-anim -camera-back none -camera-front none
          script: |
            # Ensure Chrome present
            if ! adb shell pm list packages | grep -q com.android.chrome; then
              test -n "${CHROME_APK_URL}" || { echo "Missing CHROME_APK_URL secret"; exit 1; }
              curl -L -o chrome.apk "${CHROME_APK_URL}"
              adb install -r chrome.apk
            fi
            adb shell pm list packages | grep com.android.chrome

            # Start Appium with chromedriver plugin
            npx appium plugin install --source=npm appium-chromedriver
            npx appium --use-plugins=chromedriver --base-path /wd/hub --log-level info & sleep 6

            adb devices
            npx wdio run wdio.conf.ts --spec test/specs/smoke.web.e2e.ts

      - name: Generate Allure (web)
        if: ${{ hashFiles('allure-results/**') != '' }}
        run: npx allure-commandline generate --clean ./allure-results -o ./allure-report

      - name: Upload Allure results (web)
        if: ${{ hashFiles('allure-results/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-allure-results
          path: allure-results

      - name: Upload Allure report (web)
        if: ${{ hashFiles('allure-report/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-allure-report
          path: allure-report

      - name: Collect diagnostics (web)
        if: ${{ failure() }}
        run: |
          adb logcat -d > web-logcat.txt || true
          adb shell getprop > web-getprop.txt || true
        shell: bash

      - name: Upload diagnostics (web)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: web-diagnostics
          path: |
            web-logcat.txt
            web-getprop.txt
