name: Android CI (native)

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch: {}

jobs:
  native:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Boots an emulator and runs your WDIO native smoke inside the action
      - name: Boot emulator + run native smoke
        # If you absolutely need green for a demo, uncomment the next line:
        # continue-on-error: true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_5
          avd-name: Pixel_5
          force-avd-creation: true
          disable-animations: false # avoid flaky built-in toggle
          emulator-boot-timeout: 1200
          emulator-options: >-
            -no-window -no-boot-anim -no-audio
            -camera-back none -camera-front none
            -gpu swiftshader_indirect -accel off
            -no-snapshot-load -no-snapshot-save
          script: |
            set -e

            # ADB can be flaky on cold boots; ensure it's up
            adb kill-server || true
            adb start-server
            adb wait-for-device
            adb devices

            # Best-effort unlock + turn animations off (don't fail if it hiccups)
            adb shell input keyevent 82 || true
            for s in window_animation_scale transition_animation_scale animator_duration_scale; do
              adb shell settings put global $s 0 || true
            done

            # Ensure UiAutomator2 driver (idempotent)
            npx appium driver list --installed | grep -q uiautomator2 || npx appium driver install uiautomator2 || true

            # Start Appium and give it a moment
            npx appium --base-path /wd/hub --log-level warn & sleep 10

            # Run smoke; retry once if it flakes
            npx wdio run wdio.ci.conf.ts --spec test/specs/smoke.native.e2e.ts || {
              echo "Retrying smoke once…"
              sleep 8
              adb start-server
              npx wdio run wdio.ci.conf.ts --spec test/specs/smoke.native.e2e.ts
            }

      - name: Generate Allure (native)
        if: ${{ hashFiles('allure-results/**') != '' }}
        run: npx allure-commandline generate --clean ./allure-results -o ./allure-report

      - name: Upload Allure results (native)
        if: ${{ hashFiles('allure-results/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: native-allure-results
          path: allure-results

      - name: Upload Allure report (native)
        if: ${{ hashFiles('allure-report/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: native-allure-report
          path: allure-report
